<?php
/**
 * HumanElement_Base General Component
 *
 * @category    HumanElement
 * @package     HumanElement_Base
 * @author      HumanElement Team <info@human-elemenct.com>
 * @copyright   HumanElement (https://www.human-element.com)
 */
?>
<div style="background:#EAF0EE;border:1px solid #CCCCCC;margin-bottom:10px;padding:11px 0 0 10px;">
    <h4>
        <img width="224px" style="padding-left: 15px;" src="<?php echo $this->getViewFileUrl('HumanElement_Base::images/he_logo.png') ?>" />
        <br><br>
        <div style="padding-left: 15px;">
            <p>
                <strong style="color:#EA7601;"><?php echo __('Base v') ?><?php echo $this->getModuleVersion() ?><?php echo __(' by') ?></strong>
                <a target="_blank" href="https://www.human-element.com/"><strong>Human Element</strong></a>
            </p>
        </div>
    </h4>
</div>